export default {
  'UserService': () => import('./user.test'),
  'FormService': () => import('./form.test'),
  'InterviewService': () => import('./interview.test'),
  'SurveyService': () => import('./survey.test'),
  'RespondentService': () => import('./respondent.test'),
  'RosterService': () => import('./roster.test'),
  'GeoService': () => import('./geo.test'),
  'EdgeService': () => import('./edge.test'),
  'StudyService': () => import('./study.test'),
  'InterviewManager': () => import('./interview-manager.spec'),
  'ConditionAssignment': () => import('./condition-assignment.spec'),
  'SkipService': () => import('./skip-service.test'),
  'Transactions': () => import('./transactions.test'),
  'DiffService': () => import('./diff-service.test'),
  'Validators': () => import('./validation.test'),
  'KVStore': () => import('./kv.test'),
}
