const ActionTypes = {
  select_choice: 'select-choice',
  deselect_choice: 'deselect-choice',
  other_choice_text: 'other-choice-text',
  dk_rf: 'dk-rf',
  dk_rf_val: 'dk-rf-val',
  next: 'next',
  previous: 'previous',
  number_change: 'number-change',
  add_edge: 'add-edge',
  remove_edge: 'remove-edge',
  add_roster_row: 'add-roster-row',
  remove_roster_row: 'remove-roster-row',
  change_sort_order: 'change-sort-order',
  set_val: 'set-val',
  add_geo: 'add-geo',
  remove_geo: 'remove-geo',
  add_photo: 'add-photo',
  remove_photo: 'remove-photo',
  set_date: 'set-date',
  set_text: 'set-text',
  set_time: 'set-time',
  respondent_move: 'respondent-move',
  respondent_add_geo: 'respondent-add-geo',
  respondent_remove_geo: 'respondent-remove-geo',
  other_respondent_added: 'other-respondent-added',
  select_no_one: 'select-no-one',
  deselect_no_one: 'deselect-no-one'
}

export default ActionTypes
