export enum TrellisPermission {
  REMOVE_RESPONDENT,
  ADD_RESPONDENT,
  ADD_OTHER_RESPONDENT,
  CHANGE_RESPONDENT_GEO_CURRENT,
  VIEW_STUDIES,
  ADD_STUDY,
  EDIT_STUDY,
  REMOVE_STUDY,
  VIEW_USERS,
  ADD_USER,
  REMOVE_USER,
  EDIT_USER,
  EDIT_GEO,
  ADD_GEO,
  REMOVE_GEO,
  ADD_RESPONDENT_NAME,
  ADD_RESPONDENT_GEO,
  EDIT_RESPONDENT_NAME,
  MOVE_RESPONDENT,
  REMOVE_RESPONDENT_NAME,
  ADD_RESPONDENT_CONDITION_TAG,
  REMOVE_RESPONDENT_CONDITION_TAG,
  ADD_FORM,
  EDIT_FORM,
  REMOVE_FORM,
  VIEW_DEVICES,
  ADD_DEVICE,
  EDIT_DEVICE,
  REMOVE_DEVICE,
  ADD_GEO_TYPE,
  EDIT_GEO_TYPE,
  REMOVE_GEO_TYPE,
  VIEW_REPORTS,
  VIEW_CONFIG,
  EDIT_CONFIG,
  IMPORT_RESPONDENTS,
  VIEW_PERMISSIONS,
  EDIT_PERMISSIONS
}

export enum TrellisRole {
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  SURVEYOR = 'SURVEYOR'
}

export type PermissionMap = {
  [key in TrellisPermission]: boolean
}

